image: gitpod/workspace-mysql

ports:
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      sudo service mysql start &&
      mysql -u root -proot -e 'create database mydb;'
    command: >
      sleep infinity
