CREATE TABLE DEPT
(DEPTNO INT PRIMARY KEY, DNAME VARCHAR(255), LOC VARCHAR(255));

CREATE TABLE EMP
(EMPNO INT PRIMARY KEY, ENAME VARCHAR(255), JOB VARCHAR(255), MGR INT, HIREDATE DATE, SAL INT, COMM INT, DEPTNO INT, ROLEID INT);

CREATE TABLE PROJECTS
(PROJNO INT PRIMARY KEY, PROJNAME VARCHAR(255), STARTDATE DATE, ENDDATE DATE, DEPTNO INT);

CREATE TABLE EMP_PROJECTS
(EMPNO INT, PROJNO INT, STARTDATE DATE, ENDDATE DATE);

CREATE TABLE ROLES
(ROLEID INT PRIMARY KEY, ROLENAME VARCHAR(255));